/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { JetBrains_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";



const myFont = Open_Sans({
  weight:['300'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "TEA",
  description: "Generated by create next app",
  icons: '/favicon.ico',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <head>
        <meta name="color-scheme" content="light dark"/>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={``}>
        <div className={myFont.className}>
          {children}
          <Toaster/>
          
        </div>
      </body>
    </html>
  );
}
