import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";



const myFont = JetBrains_Mono({
  weight:['300'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "TEA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
     
      </head>
      <body className={` overflow-hidden  `}>
        <div className={myFont.className}>
          {children}
          <Toaster/>
          
        </div>
      </body>
    </html>
  );
}
